### ISSUE TITLE
[Bug] 在生成视频时发生错误：ManualTicker is not a constructor

### ISSUE THREAD

**Issue by lijiajunply** [VisActor/VMind#165]
### Version

1.2.13

### Link to Minimal Reproduction

本地测试

### Steps to Reproduce

当进行视频生成时，浏览器控制台报错：
Uncaught (in promise) TypeError: ManualTicker is not a constructor
    at index.ts:39:16
    at Generator.next (<anonymous>)
    at index.ts:23:22
    at new Promise (<anonymous>)
    at __awaiter (interval.ts:13:3)
    at _chatToVideoWasm (index.ts:35:5)
    at VMind.<anonymous> (VMind.ts:255:11)
    at Generator.next (<anonymous>)
    at VMind.ts:45:34
    at new Promise (<anonymous>)

在index.ts中，具体代码为：
```ts
const vchart = new VChart(spec, {
    renderCanvas: canvas,
    mode: 'node',
    dpr: 1,
    disableDirtyBounds: true,
    ticker: defaultTicker,
    options3d: {
      enable: true,
      alpha: 0,
      beta: 0,
      center: { x: 1030, y: 300 },
      fieldRatio: 0.8,
      light: {
        dir: [3, -2, -1],
        color: 'white',
        ambient: 0.7
      }
    }
  });
```

我的代码为:
```js
 async downlandVideo() {
      const a = document.createElement('a');
      a.href = await mind.exportVideo(this.spec, this.time, {
        VChart: VChart,
        FFmpeg: FFmpeg,
        fetchFile: fetchFile
      }) //传入图表spec和视频时长，返回ObjectURL
      a.download = `${this.title}.mp4`; //设置保存的文件名
      a.dispatchEvent(new MouseEvent('click')); //保存文件
    },
```

全部代码为:
```js
export default {
  data() {
    return {
      title: '',
      data: '',
      spec: '',
      time: ''
    };
  },
  methods: {
    handleFileUpload(event) { // 将文件转化为文本
      const file = event.target.files[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = (e) => {
          this.data = e.target.result; // 将文件内容设置为数据
        };
        reader.readAsText(file); // 读取文件内容为文本
      }
    },
    async generateChart() {
      let fieldInfo, dataset;
      if (this.data.startsWith('{') || this.data.startsWith('[')) {
        dataset = JSON.parse(this.data)
        fieldInfo = mind.getFieldInfo(dataset);
      } else {
        [fieldInfo, dataset] = mind.parseCSVData(this.data);
      }
      let {spec, time} = await mind.generateChart(this.title, fieldInfo, dataset);
      this.spec = spec
      this.time = time
      const vChart = new VChart(spec, {dom: 'chart'});
      vChart.renderSync();
    },
    async downlandVideo() {
      const a = document.createElement('a');
      a.href = await mind.exportVideo(this.spec, this.time, {
        VChart: VChart,
        FFmpeg: FFmpeg,
        fetchFile: fetchFile
      }) //传入图表spec和视频时长，返回ObjectURL
      a.download = `${this.title}.mp4`; //设置保存的文件名
      a.dispatchEvent(new MouseEvent('click')); //保存文件
    },
    async downlandGif() {
      const a = document.createElement('a');
      a.href = await mind.exportGIF(this.spec, this.time, {
        VChart: VChart,
        FFmpeg: FFmpeg,
        fetchFile: fetchFile
      }); //传入图表spec和GIF时长，返回ObjectURL
      a.download = `${this.title}.gif`; //设置保存的文件名
      a.dispatchEvent(new MouseEvent('click')); //保存文件
    }
  }
};
```

mind为vmind类型，全局变量

### Current Behavior

我在网站中的示例文件中看到：
![image](https://github.com/user-attachments/assets/ae3f8c86-8d4d-431f-b5a6-a65b8b217885)
于是便复制上来，后面发现不行，于是将代码改成下面的:

```js
const a = document.createElement('a');
      a.href = await mind.exportGIF(this.spec, this.time, {
        VChart: VChart,
        FFmpeg: FFmpeg,
        fetchFile: fetchFile
      }); //传入图表spec和GIF时长，返回ObjectURL
      a.download = `${this.title}.gif`; //设置保存的文件名
      a.dispatchEvent(new MouseEvent('click')); //保存文件
```

### Expected Behavior

是变量给错了吗

### Environment

```markdown
- OS:Win11
- Browser:Edge
- Framework:Vue@3
```

**Comment by 666haiwen** [comment]
嗨，这个问题官网示例有误，目前在导出视频时，目前还需要其他的必选参数，具体如下：
```
// 新增必选参数
import { ManualTicker, defaultTimeline } from '@visactor/vrender-core';
import { createCanvas } from 'canvas';

a.href = await mind.exportVideo(this.spec, this.time, {
        VChart: VChart,
        FFmpeg: FFmpeg,
        fetchFile: fetchFile，
        // 以下为其他必选参数
        ManualTicker,
        defaultTimeline,
        createCanvas,
})
```

**Comment by lijiajunply** [comment]
我试一下

**Comment by lijiajunply** [comment]
加了这个之后就不能生成图表了...

**Comment by lijiajunply** [comment]
```

**Comment by lijiajunply** [comment]
浏览器报错：
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createCanvas')
```

目标行：
```ts
protected bindContribution(params?: any): void | Promise<any> {
    const promiseArr: any[] = [];
    this.contributions.getContributions().forEach(contribution => {
      const data = contribution.configure(this, params);
      if ((data as any) && (data as any).then) {
        promiseArr.push(data);
      }
    });
    if (promiseArr.length) {
      return Promise.all(promiseArr);
    }
  }
```

**Comment by lijiajunply** [comment]
是在这里
```js
const vChart = new VChart(spec, {dom: 'chart'})
```

**Comment by lijiajunply** [comment]
2.11.2

**Comment by lijiajunply** [comment]
当我把引用 `import {createCanvas} from 'canvas';` 改为 `import {createCanvas as d} from 'canvas';`时，前面的报错就没了，取而代之的是：

```
TypeError: Cannot read properties of undefined (reading 'filter')
```

在container.ts 156行：
```ts
private _getNotAllArgs<T>(
    serviceIdentifier: interfaces.ServiceIdentifier<T>,
    isMultiInject: boolean,
    key?: string | number | symbol | undefined,
    value?: unknown
  ): any {
    return {
      avoidConstraints: false,
      isMultiInject, // 这个
      serviceIdentifier,
      key,
      value
    };
  }
```

**Comment by lijiajunply** [comment]
还是不行，还是会报错
这样吧，我把JS代码都复制过来：
```js
import VMind from '@visactor/vmind';
import {VChart} from "@visactor/vchart";
import {FFmpeg} from '@ffmpeg/ffmpeg'
import {fetchFile} from "@ffmpeg/util";
import {Plus} from "@element-plus/icons-vue";
import {ElMessage} from 'element-plus'
import {defaultTimeline, ManualTicker} from '@visactor/vrender-core';
import {createCanvas} from 'canvas';

const mind = new VMind({
  url: 'https://newapi.xauat.site/v1/chat/completions', // 社团的 AI URL
  model: 'gpt-4o-mini', //模型
  headers: { //
    Authorization: 'Bearer sk-qqFZNu8Fpg6uOLgjhnEsDXhSuueawhqY8BdKHggMorrualYO',
  }
});

function csvJSON(csv) {
  const lines = csv.split("\n");
  const result = [];
  const headers = lines[0].split(",");
  for (let i = 1; i < lines.length; i++) {
    const obj = {};
    const currentLine = lines[i].split(",");
    for (let j = 0; j < headers.length; j++) {
      obj[headers[j]] = currentLine[j]
    }
    result.push(obj);
  }
  return result; //JSON
}

export default {
  components: {
    Plus,
  },
  data() {
    return {
      title: '',
      data: '',
      spec: '',
      time: '',
      loading: false,
      disabled: true
    };
  },
  methods: {
    handleFileUpload(event) { // 将文件转化为文本
      const file = event.target.files[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = (e) => {
          this.data = e.target.result; // 将文件内容设置为数据
        };
        reader.readAsText(file, 'utf-8'); // 读取文件内容为文本
      }
    },
    async generateChart() {
      if (!this.data || !this.title) {
        ElMessage.error('信息没填写完')
        return
      }
      document.getElementById("chart").innerHTML = '';

      this.disabled = this.loading = true

      try {
        ElMessage({
          message: '正在生成图表，请稍等片刻',
          type: 'success',
        })

        let fieldInfo, dataset
        if (this.data.startsWith('{') || this.data.startsWith('[')) {
          dataset = JSON.parse(this.data)
        } else {
          dataset = csvJSON(this.data)
        }
        fieldInfo = mind.getFieldInfo(dataset)

        console.log(fieldInfo, dataset)
        let {spec, time} = await mind.generateChart(this.title, fieldInfo, dataset);
        this.spec = spec
        this.time = time
        const vChart = new VChart(spec, {dom: 'chart'});
        vChart.renderSync();

        this.disabled = false
      } catch (e) {
        ElMessage.error('出问题了')
        console.error(e)
      }

      this.loading = false
    },
    async downlandVideo() {
      const a = document.createElement('a');
      const ffmpeg = new FFmpeg();
      let text = await mind.exportVideo(this.spec, this.time, {
        VChart,
        // 传入ffmpeg
        FFmpeg: ffmpeg,
        fetchFile,
        ManualTicker,
        defaultTimeline,
        createCanvas
      });
      console.log(text)
      a.download = `${this.title}.mp4`; //设置保存的文件名
      a.dispatchEvent(new MouseEvent('click')); //保存文件
    },
    async downlandGif() {
      const a = document.createElement('a');
      const ffmpeg = new FFmpeg();
      a.href = await mind.exportVideo(this.spec, this.time, {
        VChart: VChart,
        FFmpeg: ffmpeg,
        fetchFile: fetchFile
      })
      a.download = `${this.title}.gif`; //设置保存的文件名
      a.dispatchEvent(new MouseEvent('click')); //保存文件
    }
  }
};
```

**Comment by lijiajunply** [comment]
还是不行，现在生成图表也不行了，两个都是报同样的错，要么就是找不着createCanvas，要么就是找不着filter
我把我这里的代码都贴一下：
```js
import VMind from '@visactor/vmind';
import {VChart} from "@visactor/vchart";
import {FFmpeg} from '@ffmpeg/ffmpeg'
import {fetchFile} from "@ffmpeg/util";
import {Plus} from "@element-plus/icons-vue";
import {ElMessage} from 'element-plus'
import {defaultTimeline, ManualTicker} from '@visactor/vrender-core';
import {createCanvas} from 'canvas';

const mind = new VMind({
  url: '', // AI
  model: 'gpt-4o-mini', //模型
  headers: { //
    Authorization: 'Bearer ',
  }
});

function csvJSON(csv) {
  const lines = csv.split("\n");
  const result = [];
  const headers = lines[0].split(",");
  for (let i = 1; i < lines.length; i++) {
    const obj = {};
    const currentLine = lines[i].split(",");
    for (let j = 0; j < headers.length; j++) {
      obj[headers[j]] = currentLine[j]
    }
    result.push(obj);
  }
  return result; //JSON
}

export default {
  components: {
    Plus,
  },
  data() {
    return {
      title: '',
      data: '',
      spec: '',
      time: '',
      loading: false,
      disabled: true
    };
  },
  methods: {
    handleFileUpload(event) { // 将文件转化为文本
      const file = event.target.files[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = (e) => {
          this.data = e.target.result; // 将文件内容设置为数据
        };
        reader.readAsText(file, 'utf-8'); // 读取文件内容为文本
      }
    },
    async generateChart() {
      if (!this.data || !this.title) {
        ElMessage.error('信息没填写完')
        return
      }
      document.getElementById("chart").innerHTML = '';

      this.disabled = this.loading = true

      try {
        ElMessage({
          message: '正在生成图表，请稍等片刻',
          type: 'success',
        })

        let fieldInfo, dataset
        if (this.data.startsWith('{') || this.data.startsWith('[')) {
          dataset = JSON.parse(this.data)
        } else {
          dataset = csvJSON(this.data)
        }
        fieldInfo = mind.getFieldInfo(dataset)

        console.log(fieldInfo, dataset)
        let {spec, time} = await mind.generateChart(this.title, fieldInfo, dataset);
        this.spec = spec
        this.time = time
        const vChart = new VChart(spec, {dom: 'chart'});
        vChart.renderSync();

        this.disabled = false
      } catch (e) {
        ElMessage.error('出问题了')
        console.error(e)
      }

      this.loading = false
    },
    async downlandVideo() {
      const a = document.createElement('a');
      const ffmpeg = new FFmpeg();
      let text = await mind.exportVideo(this.spec, this.time, {
        VChart,
        // 传入ffmpeg
        FFmpeg: ffmpeg,
        fetchFile,
        ManualTicker,
        defaultTimeline,
        createCanvas
      });
      console.log(text)
      a.download = `${this.title}.mp4`; //设置保存的文件名
      a.dispatchEvent(new MouseEvent('click')); //保存文件
    },
    async downlandGif() {
      const a = document.createElement('a');
      const ffmpeg = new FFmpeg();
      a.href = await mind.exportVideo(this.spec, this.time, {
        VChart: VChart,
        FFmpeg: ffmpeg,
        fetchFile: fetchFile
      })
      a.download = `${this.title}.gif`; //设置保存的文件名
      a.dispatchEvent(new MouseEvent('click')); //保存文件
    }
  }
};
```

以及package.json:
```json
{
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@element-plus/icons-vue": "^2.3.1",
    "@ffmpeg/ffmpeg": "^0.12.10",
    "@ffmpeg/util": "^0.12.1",
    "@visactor/vchart": "^1.12.13",
    "@visactor/vmind": "^1.2.13",
    "@visactor/vrender-core": "^0.21.0",
    "canvas": "^2.11.2",
    "element-plus": "^2.9.0",
    "vue": "^3.5.13"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.2.1",
    "vite": "^6.0.1"
  }
}
```

**Comment by 666haiwen** [comment]
麻烦加下飞书群交流下吧～
[二维码](https://lf-dp.bytetos.com/obj/dp-open-internet-cn/visactor-site/bytedance/client/img/common/lark-group.jpeg)

**Comment by 666haiwen** [comment]
可以参考这个解决问题，https://codesandbox.io/p/sandbox/flamboyant-smoke-rgy6jq， sandbox无法直接运行源于webpack

**Comment by lijiajunply** [comment]
搞定了，谢谢

**Comment by liuninggxy** [comment]
> 搞定了，谢谢

@lijiajunply 您好，请问这个问题您是怎么解决的呢，我在VMind2.0.5中遇到了同样的问题，显示TypeError: createCanvas is not a function
